JBlog.Web/Areas/Admin/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminController : Controller
    {
    }
}

JBlog.Web/Areas/Admin/Controllers/ArticleController.cs
using JBlog.Application.AppInterfaces;
using JBlog.Application.AppServices;
using JBlog.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Areas.Admin.Controllers
{
    public class ArticleController : AdminController
    {
        private readonly IArticleAppService _articleAppService;
        private readonly ICategoryAppService _categoryAppService;

        public ArticleController(IArticleAppService articleAppService, ICategoryAppService categoryAppService)
        {
            _articleAppService = articleAppService;
            _categoryAppService = categoryAppService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _articleAppService.GetListAsync();
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var model = new ArticleViewModel();
            if (id.HasValue)
            {
                model = await _articleAppService.GetByIdAsync(id.Value);
            }

            var categories = await _categoryAppService.GetListAsync();
            ViewBag.Categories = categories;
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _articleAppService.GetByIdAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Save(ArticleViewModel viewModel)
        {
            if (viewModel.Id > 0)
            {
                await _articleAppService.UpdateAsync(viewModel);
            }
            else
            {
                await _articleAppService.AddAsync(viewModel);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            await _articleAppService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

JBlog.Web/Areas/Admin/Controllers/CategoryController.cs
using JBlog.Application.AppInterfaces;
using JBlog.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Areas.Admin.Controllers
{
    public class CategoryController : AdminController
    {
        private readonly ICategoryAppService _categoryAppService;

        public CategoryController(ICategoryAppService categoryAppService)
        {
            _categoryAppService = categoryAppService;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _categoryAppService.GetListAsync();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View("Edit");
        }

        public IActionResult Test()
        {
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = await _categoryAppService.GetByIdAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _categoryAppService.GetByIdAsync(id);
            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Save(CategoryViewModel viewModel)
        {
            if (viewModel.Id > 0)
            {
                await _categoryAppService.UpdateAsync(viewModel);
            }
            else
            {
                await _categoryAppService.AddAsync(viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            await _categoryAppService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

JBlog.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Areas.Admin.Controllers
{
    public class HomeController : AdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

JBlog.Web/Controllers/ArticleController.cs
using JBlog.Application.AppInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleAppService _articleAppService;

        public ArticleController(IArticleAppService articleAppService)
        {
            _articleAppService = articleAppService;
        }

        public async Task<IActionResult> Index(int id)
        {
          var model= await _articleAppService.GetByIdAsync(id);
            return View(model);
        }
    }
}

JBlog.Web/Controllers/HomeController.cs
using JBlog.Application.AppInterfaces;
using JBlog.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IArticleAppService _articleAppService;

        public HomeController(IArticleAppService articleAppService)
        {
            _articleAppService = articleAppService;
        }

        public async Task<IActionResult> Index(int page = 1, int size = 10)
        {
            var query = new ArticleQuery
            {
                Page = page,
                PageSize = size
            };
            var model = await _articleAppService.GetListAsync(query);
            return View(model);
        }


        public IActionResult Article(int id)
        {
            return View();
        }


    }
}

JBlog.Web/Views/Shared/Components/LeftMenu/LeftMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Views.Shared.Components.LeftMenu
{
    public class LeftMenuViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

JBlog.Web/Views/Shared/Components/SideBar/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace JBlog.Web.Views.Shared.Components.SideBar
{
    public class SideBarViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

JBlog.Web/Areas/Admin/Views/Article/Delete.cshtml
@model JBlog.Application.ViewModels.ArticleViewModel
<form  asp-action="ConfirmDelete" method="post">
    <div class="card card-danger">
        <div class="card-header">
            <h3 class="card-title">删除警告</h3>
        </div>
        <div class="card-body">
            确认删除文章【@(Model.Title)】？
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" asp-action="ConfirmDelete" asp-route-id="@Model.Id">确认</button>
            <a class="btn btn-default" asp-action="Index">取消</a>
        </div>
    </div>
</form>

JBlog.Web/Areas/Admin/Views/Article/Edit.cshtml
@using JBlog.Application.ViewModels
@model JBlog.Application.ViewModels.ArticleViewModel
<form asp-area="Admin" asp-controller="Article" asp-action="Save" method="post">
    <div class="card">
        <div class="card-body">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreateOn" />
            <input type="hidden" asp-for="PublishOn" />
            <div class="form-group">
                <label asp-for="Title">标题</label>
                <input type="text" class="form-control" asp-for="Title" placeholder="请输入文章标题">
            </div>
            <div class="form-group">
                <label asp-for="CategoryId">分类</label>
                <select class="custom-select" asp-for="CategoryId">
                    @foreach (CategoryViewModel category in ViewBag.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>标签</label>
                <div class="select2-purple">
                    <select class="select2" multiple="multiple" data-placeholder="创建或选择标签" data-dropdown-css-class="select2-purple" style="width: 100%;">
                    </select>
                </div>

            </div>
            <div class="form-group">
                <input type="hidden" asp-for="@Model.Content" />
                <input type="hidden" asp-for="@Model.HtmlContent" />
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" asp-for="IsPublished" value="True">
                    <label asp-for="IsPublished" class="custom-control-label">立即发布</label>
                </div>
            </div>
        </div>
        <div class="card-footer">

            <button type="submit" class="btn btn-primary">保存</button>

        </div>
    </div>
</form>

@section styles
    {
    <link href="~/lib/wangeditor5/css/style.min.css" rel="stylesheet" />
    <style>
        #editor-wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
}

@section scripts
    {
    <script src="~/lib/wangeditor5/index.min.js"></script>

    <script>
        const { createEditor, createToolbar } = window.wangEditor
        const editorConfig = {
            placeholder: '请输入内容...',
            onChange(editor) {
                const html = editor.getHtml()
                const text = editor.getText()
                // 也可以同步到 <textarea>
                $("#Content").val(text)
                $("#HtmlContent").val(html)
            }
        }

        const editor = createEditor({
            selector: '#editor-container',
            html: `@Html.Raw(Model.HtmlContent)`,
            config: editorConfig,
            mode: 'default', // or 'simple'
        })
        const toolbarConfig = {}

        const toolbar = createToolbar({
            editor,
            selector: '#toolbar-container',
            config: toolbarConfig,
            mode: 'default', // or 'simple'
        })
        var tags = [
            { id: 1, text: 'HTML' },
            { id: 2, text: 'CSS' },
            { id: 3, text: 'JavaScript' }
        ];
        $('.select2').select2({
            tags: true,
            //theme: 'bootstrap4',
            tokenSeparators: [',', ' '],
            createTag: function (params) {
                return {
                    id: params.term,
                    text: params.term
                }
            },
            data: tags
        });
    </script>

}

JBlog.Web/Areas/Admin/Views/Article/Write.cshtml
@model JBlog.Application.ViewModels.ArticleWriteViewModel
<form asp-area="Admin" asp-controller="Article" asp-action="Write" method="post">
    <div class="card">
        <div class="card-body">
            <div class="form-group">
                <label for="txtTitle">标题</label>
                <input type="text" class="form-control" id="txtTitle" placeholder="请输入文章标题">
            </div>
            <div class="form-group">
                <label for="txtCategoryId">分类</label>
                <select class="custom-select" id="txtCategoryId">
                    <option>Value 1</option>
                    <option>Value 2</option>
                    <option>Value 3</option>
                </select>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="@Model.Content"/>
                <input type="hidden" asp-for="@Model.HtmlContent"/>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-default" asp-area="Admin" asp-controller="Article" asp-action="SaveDraft">存为草稿</button>
            <button type="submit" class="btn btn-primary" asp-area="Admin" asp-controller="Article" asp-action="Publish">立即发布</button>
        </div>
    </div>
</form>

@section styles
    {
    <link href="~/lib/wangeditor5/css/style.min.css" rel="stylesheet" />
    <style>
        #editor-wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
}

@section scripts
    {
    <script src="~/lib/wangeditor5/index.min.js"></script>
    <script>
        const { createEditor, createToolbar } = window.wangEditor
        const editorConfig = {
            placeholder: '请输入内容...',
            onChange(editor) {
                const html = editor.getHtml()
                const text = editor.getText()
                console.log('editor content', html)
                // 也可以同步到 <textarea>
                $("#Content").val(text)
                $("#HtmlContent").val(html)
            }
        }

        const editor = createEditor({
            selector: '#editor-container',
            html: '<p><br></p>',
            config: editorConfig,
            mode: 'default', // or 'simple'
        })

        const toolbarConfig = {}

        const toolbar = createToolbar({
            editor,
            selector: '#toolbar-container',
            config: toolbarConfig,
            mode: 'default', // or 'simple'
        })
    </script>

}

JBlog.Web/Areas/Admin/Views/Category/Create.cshtml
@model JBlog.Application.ViewModels.CategoryViewModel
<div class="card">
    <form asp-area="Admin" asp-controller="Category" asp-action="Save" method="post">
        <div class="card-body">
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name">名称</label>
                <input type="text" class="form-control" asp-for="Name" placeholder="输入名称">
            </div>
            <div class="form-group">
                <label asp-for="Description">描述</label>
                <textarea class="form-control" asp-for="Description" rows="3" ></textarea>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">保存</button>
        </div>
    </form>
</div>

JBlog.Web/Areas/Admin/Views/Category/Delete.cshtml
@model JBlog.Application.ViewModels.CategoryViewModel
<form asp-area="Admin" asp-controller="Category" asp-action="ConfirmDelete" method="post">
    <div class="card card-danger">
        <div class="card-header">
            <h3 class="card-title">删除警告</h3>
        </div>
        <div class="card-body">
            确认删除分类【@(Model.Name)】？
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" asp-action="ConfirmDelete" asp-route-id="@Model.Id">确认</button>
            <a class="btn btn-default" asp-action="Index">取消</a>
        </div>
    </div>
</form>

JBlog.Web/Areas/Admin/Views/Category/Edit.cshtml
@model JBlog.Application.ViewModels.CategoryViewModel
<div class="card">
    <div class="card-header text-right">
        <a class="btn btn-tool" asp-action="Index" title="返回">
            <i class="fas fa-reply"></i>
        </a>
    </div>
    <form asp-area="Admin" asp-controller="Category" asp-action="Save" method="post">
        <div class="card-body">
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name">名称</label>
                <input type="text" class="form-control" asp-for="Name" placeholder="输入名称">
            </div>
            <div class="form-group">
                <label asp-for="Description">描述</label>
                <textarea class="form-control" asp-for="Description" rows="3" ></textarea>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">保存</button>
        </div>
    </form>
</div>

JBlog.Web/Areas/Admin/Views/Category/Index.cshtml
@model IList<JBlog.Application.ViewModels.CategoryViewModel>
<div class="card">
    <div class="card-header">
        <a class="btn btn-primary" asp-area="Admin" asp-controller="Category" asp-action="Create">添加分类</a>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 20px">#</th>
                    <th>名称</th>
                    <th>描述</th>
                    <th style="width: 160px">操作</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var index = 1;
                    foreach (var category in Model)
                    {
                        <tr>
                            <td>@(index++)</td>
                            <td>@category.Name</td>
                            <td>@category.Description</td>
                            <td>
                                <a class="btn btn-sm btn-warning" asp-area="Admin" asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id">修改</a>
                                <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@category.Id">删除</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

    <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
            <li class="page-item"><a class="page-link" href="#">«</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">»</a></li>
        </ul>
    </div>
</div>

JBlog.Web/Areas/Admin/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

JBlog.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Fixed Sidebar</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/lib/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/admin-lte/css/adminlte.css">
    @await RenderSectionAsync("styles",false)
</head>
<body class="hold-transition sidebar-mini layout-fixed">

    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item">
                    <span class="nav-link">JBlog Admin</span>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/lib/admin-lte/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>
                <nav class="mt-2">

                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="../widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    站点监控
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Article" asp-action="Edit" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    写文章
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Article" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    文章列表
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    分类管理
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    专题管理
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
        </aside>

        <div class="content-wrapper">

            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Fixed Layout</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Layout</a></li>
                                <li class="breadcrumb-item active">Fixed Layout</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </section>

            <section class="content">
                @RenderBody()
            </section>

        </div>

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.2.0
            </div>
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
        </footer>

        <aside class="control-sidebar control-sidebar-dark">

        </aside>

    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/admin-lte/js/adminlte.min.js"></script>
    @await RenderSectionAsync("scripts",false)
</body>
</html>

JBlog.Web/Views/Home/Index.cshtml
@model JBlog.Common.Models.PageResult<JBlog.Application.ViewModels.ArticleViewModel>
@{
    ViewBag.isShow = true;
}

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-title">
                    <div class="row">
                        <div class="col-md-9 col-xs-12">
                            <h2><span>News and Stories</span></h2>

                            <p class="subtitle text-muted">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Proin gravida nibh vel velit auctor Aenean sollicitudin, adipisicing elit sed lorem quis bibendum auctor.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="pb-5">
    <div class="container">
        <div class="row pt-5">
            <div class="col-xl-8">
                @foreach (var article in Model.Records)
                {

                    <article class="post">

                        <div class="post-header">
                            <h2 class="post-title"><a asp-controller="Article" asp-action="Index" asp-route-id="@article.Id">@article.Title</a></h2>
                            <ul class="post-meta">
                                <li><i class="mdi mdi-calendar"></i> @article.CreateOn</li>
                                <li><i class="mdi mdi-tag-text-outline"></i> <a asp-controller="Article" asp-action="Index" asp-route-id="@article.Id">@article.CategoryName</a></li>
                                <li><i class="mdi mdi-comment-multiple-outline"></i> <a asp-controller="Article" asp-action="Index" asp-route-id="@article.Id">3 Comments</a></li>
                            </ul>
                        </div>

                        <div class="post-preview">
                            <a asp-controller="Article" asp-action="Index" asp-route-id="@article.Id"><img src="images/blog/blog-1.jpg" alt="" class="img-fluid rounded"></a>
                        </div>

                        <div class="post-content">
                            <p>@Html.Raw(article.Content.Substring(0,200))</p>

                        </div>

                        <div><a asp-controller="Article" asp-action="Index" asp-route-id="@article.Id" class="btn btn-outline-custom">Read More <i class="mdi mdi-arrow-right"></i></a></div>

                    </article>
                }
                <!-- Pagination-->
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="pagination">
                            <li class="next"><a href="index.html#"><i class="mdi mdi-chevron-left"></i></a></li>
                            <li class="active"><a href="index.html#">1</a></li>
                            <li><a href="index.html#">2</a></li>
                            <li><a href="index.html#">3</a></li>
                            <li><a href="index.html#">4</a></li>
                            <li><a href="index.html#">5</a></li>
                            <li class="prev"><a href="index.html#"><i class="mdi mdi-chevron-right"></i></a></li>
                        </ul>
                    </div>
                </div>
                <!-- Pagination end-->
            </div>
            <div class="col-xl-4">
                @await Component.InvokeAsync("SideBar")
            </div>
        </div>
    </div>
</section>

JBlog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Responsive blog template">
    <meta name="author" content="Zoyothemes">
    <link rel="shortcut icon" href="~/images/favicon.ico">
    <title>BugChang's Blog - @ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,600,700" rel="stylesheet">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/metisMenu/metisMenu.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/materialdesign-webfont/css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/default.css" rel="stylesheet" type="text/css" />
    @await RenderSectionAsync("css",false)
</head>
<body>
    <div id="wrapper">
        @await Component.InvokeAsync("LeftMenu")
        <div class="page-wrapper">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/lib/metismenu/metismenu.min.js"></script>
    <script src="~/js/jquery.app.js"></script>
    @await RenderSectionAsync("scripts",false)
</body>
</html>